// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fajarachmadyusup13/gathering-app/internal/model (interfaces: GatheringRepository)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/fajarachmadyusup13/gathering-app/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockGatheringRepository is a mock of GatheringRepository interface.
type MockGatheringRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGatheringRepositoryMockRecorder
}

// MockGatheringRepositoryMockRecorder is the mock recorder for MockGatheringRepository.
type MockGatheringRepositoryMockRecorder struct {
	mock *MockGatheringRepository
}

// NewMockGatheringRepository creates a new mock instance.
func NewMockGatheringRepository(ctrl *gomock.Controller) *MockGatheringRepository {
	mock := &MockGatheringRepository{ctrl: ctrl}
	mock.recorder = &MockGatheringRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatheringRepository) EXPECT() *MockGatheringRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGatheringRepository) Create(arg0 context.Context, arg1 *model.Gathering) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGatheringRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGatheringRepository)(nil).Create), arg0, arg1)
}

// DeleteByID mocks base method.
func (m *MockGatheringRepository) DeleteByID(arg0 context.Context, arg1 int64) (*model.Gathering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Gathering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockGatheringRepositoryMockRecorder) DeleteByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockGatheringRepository)(nil).DeleteByID), arg0, arg1)
}

// FindByID mocks base method.
func (m *MockGatheringRepository) FindByID(arg0 context.Context, arg1 int64) (*model.Gathering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Gathering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockGatheringRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockGatheringRepository)(nil).FindByID), arg0, arg1)
}

// UpdateByID mocks base method.
func (m *MockGatheringRepository) UpdateByID(arg0 context.Context, arg1 *model.Gathering) (*model.Gathering, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", arg0, arg1)
	ret0, _ := ret[0].(*model.Gathering)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockGatheringRepositoryMockRecorder) UpdateByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockGatheringRepository)(nil).UpdateByID), arg0, arg1)
}
