services:
  # MySQL service
  mysql:
    image: mysql:latest
    container_name: "mysql_db"
    environment:
      MYSQL_ROOT_PASSWORD: gits123
      MYSQL_DATABASE: gathering_app
      MYSQL_USER: gits
      MYSQL_PASSWORD: gits123
    ports:
      - "3306:3306"
    volumes:
      - "./sito/db/:/var/lib/mysql"

  # Go service
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    restart: on-failure:10
    ports:
      - "0.0.0.0:1212:1212"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: gits123
      MYSQL_DB: gathering_app
  