services:
  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gathering_app
      MYSQL_USER: root
      MYSQL_PASSWORD: gits123
    ports:
      - "3308:3308"
    networks:
      - fullstack
    volumes:
      - "./sito/db/:/var/lib/mysql"

  # Go service
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "1212:1212"
    networks:
      - fullstack
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3308
      MYSQL_USER: root
      MYSQL_PASSWORD: gits123
      MYSQL_DB: gathering_app

networks:
  fullstack:
    driver: bridge

  